export const JOB_ANALYSIS_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    job: {
      type: "object",
      additionalProperties: false,
      properties: {
        company: { type: "string" },
        role: { type: "string" },
        location: { type: "string" },
        employmentType: { type: "string" },
        seniority: { type: "string" },
        summary: { type: "string" },
        requirements: { type: "array", items: { type: "string" } },
        responsibilities: { type: "array", items: { type: "string" } },
        keywords: { type: "array", items: { type: "string" } },
        compensation: { type: "string" },
        remotePolicy: { type: "string" },
      },
      required: [
        "company",
        "role",
        "location",
        "employmentType",
        "seniority",
        "summary",
        "requirements",
        "responsibilities",
        "keywords",
        "compensation",
        "remotePolicy",
      ],
    },
    fit: {
      type: "object",
      additionalProperties: false,
      properties: {
        score: { type: "integer", minimum: 0, maximum: 100 },
        verdict: {
          type: "string",
          enum: ["excellent", "strong", "mixed", "weak"],
        },
        strongestMatches: { type: "array", items: { type: "string" } },
        gaps: { type: "array", items: { type: "string" } },
        hardBlockers: { type: "array", items: { type: "string" } },
        recommendation: { type: "string" },
      },
      required: [
        "score",
        "verdict",
        "strongestMatches",
        "gaps",
        "hardBlockers",
        "recommendation",
      ],
    },
    company: {
      type: "object",
      additionalProperties: false,
      properties: {
        summary: { type: "string" },
        product: { type: "string" },
        stage: { type: "string" },
        size: { type: "string" },
        funding: { type: "string" },
        engineeringSignals: { type: "array", items: { type: "string" } },
        risks: { type: "array", items: { type: "string" } },
        sources: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              title: { type: "string" },
              url: { type: "string" },
            },
            required: ["title", "url"],
          },
        },
      },
      required: [
        "summary",
        "product",
        "stage",
        "size",
        "funding",
        "engineeringSignals",
        "risks",
        "sources",
      ],
    },
    suggestions: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          fieldId: { type: "string" },
          label: { type: "string" },
          action: { type: "string", enum: ["fill", "review", "skip"] },
          value: { type: "string" },
          confidence: {
            type: "string",
            enum: ["high", "medium", "low"],
          },
          evidence: { type: "string" },
          warning: { type: "string" },
        },
        required: [
          "fieldId",
          "label",
          "action",
          "value",
          "confidence",
          "evidence",
          "warning",
        ],
      },
    },
    missingFacts: { type: "array", items: { type: "string" } },
  },
  required: ["job", "fit", "company", "suggestions", "missingFacts"],
} as const;
